name: khelwa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.9.3
  logging: ^1.2.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_messaging: any
  get: ^4.6.6
  get_it: ^8.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  dio: ^5.5.0+1
  fluttertoast: ^8.2.6
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  sqflite: ^2.4.0
  path: ^1.9.0





  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
          weight: 800
